# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.0].define(version: 2025_02_09_214201) do
  create_table "items", force: :cascade do |t|
    t.integer "order_id", null: false
    t.decimal "unit_quantity"
    t.decimal "product_value"
    t.decimal "flex_product_value"
    t.decimal "discount_value"
    t.decimal "increase_value"
    t.decimal "gross_total_value"
    t.decimal "flex_base_value"
    t.text "observation"
    t.integer "loading_number"
    t.string "unit_code"
    t.string "status"
    t.integer "product_code"
    t.integer "sequential"
    t.string "route_code"
    t.date "movement_date"
    t.date "lowering_date"
    t.integer "quantity"
    t.integer "package_quantity"
    t.decimal "discount_percentage"
    t.decimal "total_value"
    t.decimal "commission_value"
    t.integer "original_quantity"
    t.decimal "sale_price"
    t.decimal "flex_value"
    t.decimal "unit_value"
    t.integer "client_order_item_number"
    t.integer "order_number"
    t.string "icms_symbol"
    t.decimal "icms_aliquot"
    t.decimal "icms_reduction_base"
    t.integer "stock_code"
    t.string "series"
    t.date "wms_valid_date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_id"], name: "index_items_on_order_id"
  end

  create_table "order_payment_items", force: :cascade do |t|
    t.integer "order_payment_id", null: false
    t.string "lowering_account"
    t.integer "installment"
    t.string "host_nsu"
    t.string "sitef_nsu"
    t.string "authorization_nsu"
    t.string "authorizer"
    t.string "card_bin"
    t.string "bank"
    t.string "agency"
    t.decimal "value"
    t.string "pix_id"
    t.string "ecomm_transaction_id"
    t.string "card_flag"
    t.string "payer_cnpj"
    t.string "payer_state"
    t.string "receiver_cnpj"
    t.string "payment_terminal_id"
    t.string "payment_date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_payment_id"], name: "index_order_payment_items_on_order_payment_id"
  end

  create_table "order_payments", force: :cascade do |t|
    t.integer "order_id", null: false
    t.string "payment_method"
    t.string "nfe_flag_code"
    t.string "payment_institution_cnpj"
    t.decimal "change_value"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_id"], name: "index_order_payments_on_order_id"
  end

  create_table "orders", force: :cascade do |t|
    t.string "transaction_identifier"
    t.string "unit_code"
    t.integer "loading_number"
    t.string "status"
    t.date "movement_date"
    t.date "delivery_date"
    t.time "lcto_time"
    t.date "base_date"
    t.date "lowering_date"
    t.string "route_code"
    t.string "payment_code"
    t.decimal "freight_percentage"
    t.decimal "discount_value"
    t.decimal "discount_percentage"
    t.decimal "additional_expense_value"
    t.decimal "additional_expense_percentage"
    t.decimal "commission_value"
    t.string "lowering_transaction"
    t.string "coupon_number"
    t.string "lowering_pdv_code"
    t.string "lowering_pdv_unit"
    t.integer "delivery_sequence"
    t.integer "user_code"
    t.integer "kind_code"
    t.integer "client_link_code"
    t.integer "consolidated_number"
    t.integer "production_transaction_number"
    t.date "estimated_date"
    t.string "delivery_shift"
    t.string "unit"
    t.string "origin"
    t.string "withdrawal_unit"
    t.date "date"
    t.integer "client_code"
    t.string "payment_method"
    t.string "client_order_number"
    t.string "seller_code"
    t.text "observation"
    t.integer "kind"
    t.decimal "discount"
    t.string "document_code"
    t.string "name"
    t.string "email"
    t.string "cpf"
    t.string "rg"
    t.string "cnpj"
    t.string "state_registration"
    t.string "address"
    t.string "number"
    t.string "complement"
    t.string "neighborhood"
    t.integer "city"
    t.string "zip_code"
    t.string "phone"
    t.string "delivery_turn"
    t.date "expected_date"
    t.decimal "freight_value"
    t.decimal "accessory_expense"
    t.string "carrier"
    t.string "route"
    t.string "deliverer"
    t.text "additional_data"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "products", force: :cascade do |t|
    t.integer "code", null: false
    t.integer "sku"
    t.string "barcode"
    t.string "ncm_code"
    t.string "description"
    t.string "complement"
    t.string "brand"
    t.string "status"
    t.decimal "price"
    t.string "group"
    t.string "offer"
    t.date "offer_date"
    t.decimal "normal_price"
    t.string "unit_code"
    t.string "department_code"
    t.string "department"
    t.boolean "active"
    t.string "tax_code"
    t.integer "stock"
    t.integer "stock1"
    t.integer "stock2"
    t.integer "stock3"
    t.integer "stock4"
    t.integer "stock5"
    t.decimal "list_price"
    t.decimal "pdv_price"
    t.decimal "pdv_price3"
    t.decimal "pdv_price4"
    t.decimal "pdv_price5"
    t.decimal "label_price"
    t.decimal "poster_price"
    t.decimal "sale_price2"
    t.decimal "sale_price3"
    t.decimal "sale_price4"
    t.decimal "sale_price5"
    t.decimal "factor_pr3"
    t.decimal "factor_pr4"
    t.decimal "factor_pr5"
    t.integer "stock_code"
    t.integer "minimum_stock"
    t.integer "maximum_stock"
    t.integer "average_daily_sale"
    t.decimal "space"
    t.string "cashier_code"
    t.decimal "purchase_cost"
    t.decimal "company_cost"
    t.decimal "tax_cost"
    t.decimal "average_cost"
    t.decimal "transfer_cost"
    t.decimal "sale_cost"
    t.string "store_sector"
    t.string "deposit_sector"
    t.decimal "unit_price_measure"
    t.string "pdv_description"
    t.string "blocked"
    t.decimal "height"
    t.decimal "width"
    t.decimal "depth"
    t.decimal "weight"
    t.decimal "net_weight"
    t.string "client_description"
    t.decimal "temperature"
    t.string "package_type"
    t.integer "package_quantity"
    t.string "changed_product"
    t.integer "etq"
    t.integer "ctz"
    t.string "key"
    t.integer "replenishment_term"
    t.integer "delivery_term"
    t.integer "security_days"
    t.integer "validity"
    t.integer "minimum_validity"
    t.string "marked"
    t.decimal "previous_sale_price"
    t.date "sale_price_date"
    t.integer "sale_price_user"
    t.decimal "margin"
    t.decimal "minimum_margin"
    t.integer "offer_quantity"
    t.date "offer_start_date"
    t.date "last_purchase_date"
    t.decimal "last_purchase_price"
    t.integer "last_purchase_quantity"
    t.string "last_purchase_symbol"
    t.decimal "last_purchase_reduction_bc"
    t.integer "last_supplier"
    t.date "costs_date"
    t.decimal "commission"
    t.decimal "cost_difference"
    t.decimal "sale_difference"
    t.string "magnetic_label"
    t.integer "store_quantity"
    t.date "store_date"
    t.date "previous_offer_date"
    t.decimal "previous_offer_price"
    t.decimal "previous_normal_price"
    t.string "sale_type_change"
    t.decimal "cost_difference1"
    t.decimal "cost_difference2"
    t.decimal "cost_difference3"
    t.decimal "cost_difference4"
    t.decimal "cost_difference5"
    t.decimal "sale_difference1"
    t.decimal "sale_difference2"
    t.decimal "sale_difference3"
    t.decimal "sale_difference4"
    t.decimal "sale_difference5"
    t.decimal "previous_purchase_cost"
    t.decimal "previous_average_cost"
    t.decimal "previous_tax_cost"
    t.decimal "previous_company_cost"
    t.decimal "previous_transfer_cost"
    t.decimal "previous_last_purchase_price"
    t.string "transfer_average_cost"
    t.string "acquisition"
    t.string "extra1"
    t.string "extra2"
    t.string "extra3"
    t.integer "extra4"
    t.integer "extra5"
    t.integer "extra6"
    t.integer "extra7"
    t.integer "extra8"
    t.integer "extra9"
    t.string "product_extra1"
    t.string "product_extra2"
    t.string "product_extra3"
    t.integer "product_extra4"
    t.integer "product_extra5"
    t.string "product_extra6"
    t.string "product_extra7"
    t.integer "product_extra8"
    t.integer "product_extra9"
    t.date "update_date"
    t.integer "update_user"
    t.integer "fronts"
    t.integer "origin_code"
    t.decimal "table_price"
    t.decimal "st_credit"
    t.string "sim_code"
    t.date "previous_offer_date2"
    t.decimal "previous_offer_price2"
    t.decimal "previous_normal_price2"
    t.decimal "normal_price3"
    t.decimal "normal_price4"
    t.decimal "normal_price5"
    t.decimal "previous_normal_price3"
    t.decimal "previous_normal_price4"
    t.decimal "previous_normal_price5"
    t.decimal "previous_offer_price3"
    t.decimal "previous_offer_price4"
    t.decimal "previous_offer_price5"
    t.decimal "margin3"
    t.decimal "margin4"
    t.decimal "margin5"
    t.string "offer_type_agent"
    t.string "previous_offer_type_agent"
    t.string "previous_offer_type_agent2"
    t.string "exchange_types"
    t.decimal "default_sale_price"
    t.decimal "tax_percentage"
    t.decimal "previous_sale_price2"
    t.decimal "previous_sale_price2_2"
    t.integer "price_code"
    t.string "descriptive"
    t.string "function"
    t.string "scale"
    t.string "buyer_code"
    t.integer "allowance"
    t.integer "stock_factor"
    t.datetime "maintenance_datetime"
    t.decimal "agpr_price1"
    t.decimal "agpr_price2"
    t.decimal "agpr_price3"
    t.decimal "agpr_price4"
    t.decimal "agpr_price5"
    t.decimal "agof_price1"
    t.decimal "agof_price2"
    t.decimal "agof_price3"
    t.decimal "agof_price4"
    t.decimal "agof_price5"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "store_id"
    t.index ["code"], name: "index_products_on_code", unique: true
    t.index ["store_id"], name: "index_products_on_store_id"
  end

  create_table "stores", force: :cascade do |t|
    t.string "cnpj"
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "user_id"
    t.index ["user_id"], name: "index_stores_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "code"
    t.string "email"
    t.string "api_credential"
    t.string "password_digest"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

  add_foreign_key "items", "orders"
  add_foreign_key "order_payment_items", "order_payments"
  add_foreign_key "order_payments", "orders"
  add_foreign_key "products", "stores"
  add_foreign_key "stores", "users"
end
