class CreateProducts < ActiveRecord::Migration[8.0]
  def change
    create_table :products do |t|
      t.integer :code, null: false, index: { unique: true } # Código do produto (chave única)
      t.integer :sku
      t.string :barcode
      t.string :ncm_code
      t.string :description
      t.string :complement
      t.string :brand
      t.string :status
      t.decimal :price
      t.string :group
      t.string :offer
      t.date :offer_date
      t.decimal :normal_price
      t.string :unit_code
      t.string :department_code
      t.string :department
      t.boolean :active
      t.string :tax_code
      t.integer :stock
      t.integer :stock1
      t.integer :stock2
      t.integer :stock3
      t.integer :stock4
      t.integer :stock5
      t.decimal :list_price
      t.decimal :pdv_price
      t.decimal :pdv_price3
      t.decimal :pdv_price4
      t.decimal :pdv_price5
      t.decimal :label_price
      t.decimal :poster_price
      t.decimal :sale_price2
      t.decimal :sale_price3
      t.decimal :sale_price4
      t.decimal :sale_price5
      t.decimal :factor_pr3
      t.decimal :factor_pr4
      t.decimal :factor_pr5
      t.integer :stock_code
      t.integer :minimum_stock
      t.integer :maximum_stock
      t.integer :average_daily_sale
      t.decimal :space
      t.string :cashier_code
      t.decimal :purchase_cost
      t.decimal :company_cost
      t.decimal :tax_cost
      t.decimal :average_cost
      t.decimal :transfer_cost
      t.decimal :sale_cost
      t.string :store_sector
      t.string :deposit_sector
      t.decimal :unit_price_measure
      t.string :pdv_description
      t.string :blocked
      t.decimal :height
      t.decimal :width
      t.decimal :depth
      t.decimal :weight
      t.decimal :net_weight
      t.string :client_description
      t.decimal :temperature
      t.string :package_type
      t.integer :package_quantity
      t.string :changed_product
      t.integer :etq
      t.integer :ctz
      t.string :key
      t.integer :replenishment_term
      t.integer :delivery_term
      t.integer :security_days
      t.integer :validity
      t.integer :minimum_validity
      t.string :marked
      t.decimal :previous_sale_price
      t.date :sale_price_date
      t.integer :sale_price_user
      t.decimal :margin
      t.decimal :minimum_margin
      t.integer :offer_quantity
      t.date :offer_start_date
      t.date :last_purchase_date
      t.decimal :last_purchase_price
      t.integer :last_purchase_quantity
      t.string :last_purchase_symbol
      t.decimal :last_purchase_reduction_bc
      t.integer :last_supplier
      t.date :costs_date
      t.decimal :commission
      t.decimal :cost_difference
      t.decimal :sale_difference
      t.string :magnetic_label
      t.integer :store_quantity
      t.date :store_date
      t.date :previous_offer_date
      t.decimal :previous_offer_price
      t.decimal :previous_normal_price
      t.string :sale_type_change
      t.decimal :cost_difference1
      t.decimal :cost_difference2
      t.decimal :cost_difference3
      t.decimal :cost_difference4
      t.decimal :cost_difference5
      t.decimal :sale_difference1
      t.decimal :sale_difference2
      t.decimal :sale_difference3
      t.decimal :sale_difference4
      t.decimal :sale_difference5
      t.decimal :previous_purchase_cost
      t.decimal :previous_average_cost
      t.decimal :previous_tax_cost
      t.decimal :previous_company_cost
      t.decimal :previous_transfer_cost
      t.decimal :previous_last_purchase_price
      t.string :transfer_average_cost
      t.string :acquisition
      t.string :extra1
      t.string :extra2
      t.string :extra3
      t.integer :extra4
      t.integer :extra5
      t.integer :extra6
      t.integer :extra7
      t.integer :extra8
      t.integer :extra9
      t.string :product_extra1
      t.string :product_extra2
      t.string :product_extra3
      t.integer :product_extra4
      t.integer :product_extra5
      t.string :product_extra6
      t.string :product_extra7
      t.integer :product_extra8
      t.integer :product_extra9
      t.date :update_date
      t.integer :update_user
      t.integer :fronts
      t.integer :origin_code
      t.decimal :table_price
      t.decimal :st_credit
      t.string :sim_code
      t.date :previous_offer_date2
      t.decimal :previous_offer_price2
      t.decimal :previous_normal_price2
      t.decimal :normal_price3
      t.decimal :normal_price4
      t.decimal :normal_price5
      t.decimal :previous_normal_price3
      t.decimal :previous_normal_price4
      t.decimal :previous_normal_price5
      t.decimal :previous_offer_price3
      t.decimal :previous_offer_price4
      t.decimal :previous_offer_price5
      t.decimal :margin3
      t.decimal :margin4
      t.decimal :margin5
      t.string :offer_type_agent
      t.string :previous_offer_type_agent
      t.string :previous_offer_type_agent2
      t.string :exchange_types
      t.decimal :default_sale_price
      t.decimal :tax_percentage
      t.decimal :previous_sale_price2
      t.decimal :previous_sale_price2_2
      t.integer :price_code
      t.string :descriptive
      t.string :function
      t.string :scale
      t.string :buyer_code
      t.integer :allowance
      t.integer :stock_factor
      t.datetime :maintenance_datetime
      t.decimal :agpr_price1
      t.decimal :agpr_price2
      t.decimal :agpr_price3
      t.decimal :agpr_price4
      t.decimal :agpr_price5
      t.decimal :agof_price1
      t.decimal :agof_price2
      t.decimal :agof_price3
      t.decimal :agof_price4
      t.decimal :agof_price5

      t.timestamps
    end
  end
end
